### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kottenator** [Alem/django-bootstrap-crud-templates#7]
I've found a bug in `templatetags/bscttags.py:84`:

```py
for k,v in request.GET.iteritems():
```

This line doesn't work in Python 3. Could you, please, fix this small issue and release a new PyPI version asap? 0:-)

**Comment by kottenator** [comment]
There could be more issues about Python 3 compatibility though...

**Comment by Alem** [comment]
Hello Rostyslav,
I've modified the line and updated the PyPI package. 
Please try it out and let me know if the issue resolves.

Best Regards,
Alem

**Comment by kottenator** [comment]
Sorry for delay - I've checked your fix on the same day you posted it. And it works, thanks! ;)
